# Pipeline extending the temlplate for execution in a disconnected container.

trigger:
- master

# We execute the jobs in JobList in a disconnected container using the following .yml template.
extends:
  template: disconnected_containerized_execution_template.yml
  parameters:
    jobsList:
      - template: jobsList.yml
    requiredPreSteps:
      - task: NodeTool@0
        inputs:
           versionSpec: '12.x'
        displayName: 'Install Node.js'
      - script: |
          npm install
          npm install -g oval
          npm build
