# template to insert a step before and after user steps in every job

resources:
  containers:
    - container: mycontainer
      image: ubuntu:20.04
      options: --name mycontainer1


parameters:
  - name: 'jobsList'
    type: jobList
    default: []


jobs:
  - ${{ each job in parameters.jobsList }}: # Each job
      - ${{ each pair in job }}:  # Insert all properties other than "steps"
          ${{ if ne(pair.key, 'steps') }}:
            ${{ pair.key }}: ${{ pair.value }}
        steps:                            # Wrap the steps
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'
            target: mycontainer

          - script: |
              npm install
              npm install -g oval
              npm run build
            displayName: 'npm install and build'
            target: mycontainer

          - script: docker inspect mycontainer1 -f "{{json .NetworkSettings.Networks }}" | cut -c3-47
            target: host # reserved name for the host the worker is running on

          - script: docker network disconnect $(docker inspect mycontainer1 -f "{{json .NetworkSettings.Networks }}" | cut -c3-47) mycontainer1
            target: host # reserved name for the host the worker is running on

          - ${{ each step in job.steps }}:                # Users steps
              - ${{ each pair in job }}:
                  ${{ pair.key }}: ${{ pair.value }}
                  target:
                    container: mycontainer
                    commands: restricted

